### ISSUE TITLE
Packages do not match the requirements file

### ISSUE THREAD

**Issue by junwen-k** [P2Enjoy/kohya_ss-docker#16]
Greetings,
Thanks for creating this wrapper docker for kohya_ss.

Currently I am facing some issues setting up.
I am running on Ubuntu 22.10.
I've downloaded the compiled `*.whl` as well as `*.deb` as mentioned in the README as opposed to compiling myself.

Basically I've downloaded these files:

From [PyPI](https://pypi.org/): (kohya_ss/data)

[tensorflow-2.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl](https://files.pythonhosted.org/packages/71/f5/20795b0d2cc65da482ddb1735e630b85ef4916673967ce30a64ecb979303/tensorflow-2.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
[torch-1.13.1-cp310-cp310-manylinux1_x86_64.whl](https://files.pythonhosted.org/packages/81/58/431fd405855553af1a98091848cf97741302416b01462bbf9909d3c422b3/torch-1.13.1-cp310-cp310-manylinux1_x86_64.whl)
[torchvision-0.14.1-cp310-cp310-manylinux1_x86_64.whl](https://files.pythonhosted.org/packages/cd/d4/66de471d47a293dd52c254deff0081d7c9b8d1304b911bb3cffaa1fa956b/torchvision-0.14.1-cp310-cp310-manylinux1_x86_64.whl)
[xformers-0.0.17-cp310-cp310-manylinux2014_x86_64.whl](https://files.pythonhosted.org/packages/db/4b/9a0d2549367896f0de260977c144c6ff7b5079356e31e414d5bce6e4bdd5/xformers-0.0.17-cp310-cp310-manylinux2014_x86_64.whl)

From [Nvidia](https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/) (ubuntu2204): (kohya_ss/data/libs)

[libnvinfer8_8.6.0.12-1+cuda12.0_amd64.deb](https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/libnvinfer8_8.6.0.12-1+cuda12.0_amd64.deb)
[libnvinfer-dev_8.6.0.12-1+cuda12.0_amd64.deb](https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/libnvinfer-dev_8.6.0.12-1+cuda12.0_amd64.deb)
[libnvinfer-plugin8_8.6.0.12-1+cuda12.0_amd64.deb](https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/libnvinfer-plugin8_8.6.0.12-1+cuda12.0_amd64.deb)
[libnvinfer-plugin-dev_8.6.0.12-1+cuda12.0_amd64.deb](https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/libnvinfer-plugin-dev_8.6.0.12-1+cuda12.0_amd64.deb)

This is the output for `nvidia-smi`. I am downloading *.cuda12.0 since my CUDA version is 12.
I've installed nvidia-container-toolkit before by following this [instruction](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit).

```sh
Thu Apr 13 00:43:42 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   38C    P0     6W /  50W |      6MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2580      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
```

However, I am currently getting error when running `docker compose --profile kohya up --build`.

Seems like the process failed with the hashes mismatch error. This is very weird as I've downloaded everything from official sources.

```sh
#0 125.3 ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
#0 125.3     nvidia-cudnn-cu11==8.5.0.96 from https://files.pythonhosted.org/packages/dc/30/66d4347d6e864334da5bb1c7571305e501dcb11b9155971421bb7bb5315f/nvidia_cudnn_cu11-8.5.0.96-2-py3-none-manylinux1_x86_64.whl (from torch->triton==2.0.0):
#0 125.3         Expected sha256 402f40adfc6f418f9dae9ab402e773cfed9beae52333f6d86ae3107a1b9527e7
#0 125.3              Got        a1b11129590baa3e90cc040d742315cb75c12a113feff518f6338254b8a4d84c
```

I am by no means an expert on this topic, any guidance will be very well appreciated 🙇🏻‍♂️

**Comment by junwen-k** [comment]
After some investigation, apparently the error is different each time I run `docker compose --profile kohya up --build`. I suspect the downloading process gets interrupted or something.

Could this be due to my slow internet? Anyway I just keeps on running the same command `docker compose --profile kohya up --build` when it fails and it seems like there is progress.

**Comment by junwen-k** [comment]
According to my findings, the package do not match issue is probably due to slow internet during the downloading process.

The hash mismatch issue seems to be resolved after I switched to using LAN cable instead. However, I am currently getting a different error, and this time the error is always the same:

```sh
[+] Building 871.0s (18/23)                                                                                                                                                                                                          
 => [internal] load .dockerignore                                                                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                                                                 0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                                            0.0s
 => => transferring dockerfile: 5.22kB                                                                                                                                                                                          0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                                                                                                                                                      1.5s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:39b85bbfa7536a5feceb7372a0817649ecb2724562a38360f4d6a7782a409b14                                                                                                 0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04                                                                                                                                          1.1s
 => CACHED [ 1/17] FROM docker.io/nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04@sha256:eb5b849e629ecdcc924d0e0eb2405377792d7ca24d3bd627cc5792e763bff977                                                                           0.0s
 => [internal] load build context                                                                                                                                                                                               0.0s
 => => transferring context: 890B                                                                                                                                                                                               0.0s
 => [ 2/17] RUN <<EOF (# apt for general container dependencies...)                                                                                                                                                            88.8s
 => [ 3/17] RUN <<EOF (# python...)                                                                                                                                                                                            34.5s
 => [ 4/17] COPY ./data/libs/*.deb /docker/                                                                                                                                                                                     4.6s 
 => [ 5/17] RUN <<EOF (# cuda...)                                                                                                                                                                                             136.3s 
 => [ 6/17] WORKDIR /koyah_ss                                                                                                                                                                                                   0.0s 
 => [ 7/17] RUN <<EOF (git clone https://github.com/P2Enjoy/kohya_ss.git /koyah_ss...)                                                                                                                                          4.0s 
 => [ 8/17] COPY ./data/*.whl /docker/                                                                                                                                                                                          7.5s 
 => [ 9/17] COPY ./scripts/install-container-dep.sh ./data/*-requirements.txt /docker/                                                                                                                                          1.6s 
 => [10/17] RUN <<EOF (# tensorflow, torch, torchvision, torchaudio...)                                                                                                                                                       165.3s 
 => [11/17] RUN <<EOF (# xformers...)                                                                                                                                                                                         176.9s 
 => ERROR [12/17] RUN <<EOF (# deepspeed...)                                                                                                                                                                                  248.6s 
------                                                                                                                                                                                                                               
 > [12/17] RUN <<EOF (# deepspeed...):                                                                                                                                                                                               
#0 0.589 + pip install triton==2.0.0                                                                                                                                                                                                 
#0 1.022 Collecting triton==2.0.0                                                                                                                                                                                                    
#0 1.091   Downloading triton-2.0.0-1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (63.3 MB)                                                                                                                           
#0 6.024      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.3/63.3 MB 12.9 MB/s eta 0:00:00                                                                                                                                            
#0 6.166 Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0) (3.11.0)
#0 6.214 Collecting lit
#0 6.252   Downloading lit-15.0.6-py3-none-any.whl (89 kB)
#0 6.258      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.0/90.0 kB 21.6 MB/s eta 0:00:00
#0 6.452 Collecting cmake
#0 6.468   Downloading cmake-3.26.3-py2.py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (24.0 MB)
#0 8.337      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.0/24.0 MB 12.9 MB/s eta 0:00:00
#0 8.462 Collecting torch
#0 8.479   Downloading torch-2.0.0-cp310-cp310-manylinux1_x86_64.whl (619.9 MB)
#0 56.69      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 12.9 MB/s eta 0:00:00
#0 58.08 Collecting nvidia-cusparse-cu11==11.7.4.91
#0 58.10   Downloading nvidia_cusparse_cu11-11.7.4.91-py3-none-manylinux1_x86_64.whl (173.2 MB)
#0 71.55      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.2/173.2 MB 12.9 MB/s eta 0:00:00
#0 71.96 Collecting nvidia-nvtx-cu11==11.7.91
#0 71.97   Downloading nvidia_nvtx_cu11-11.7.91-py3-none-manylinux1_x86_64.whl (98 kB)
#0 71.98      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.6/98.6 kB 18.1 MB/s eta 0:00:00
#0 72.03 Collecting nvidia-cublas-cu11==11.10.3.66
#0 72.04   Downloading nvidia_cublas_cu11-11.10.3.66-py3-none-manylinux1_x86_64.whl (317.1 MB)
#0 96.67      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 MB 12.9 MB/s eta 0:00:00
#0 97.35 Collecting nvidia-curand-cu11==10.2.10.91
#0 97.37   Downloading nvidia_curand_cu11-10.2.10.91-py3-none-manylinux1_x86_64.whl (54.6 MB)
#0 101.6      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 MB 12.9 MB/s eta 0:00:00
#0 101.8 Collecting networkx
#0 101.8   Downloading networkx-3.1-py3-none-any.whl (2.1 MB)
#0 101.9      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 13.1 MB/s eta 0:00:00
#0 102.0 Collecting nvidia-cuda-cupti-cu11==11.7.101
#0 102.0   Downloading nvidia_cuda_cupti_cu11-11.7.101-py3-none-manylinux1_x86_64.whl (11.8 MB)
#0 102.9      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 12.9 MB/s eta 0:00:00
#0 103.0 Collecting typing-extensions
#0 103.0   Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
#0 103.0 Collecting nvidia-cusolver-cu11==11.4.0.1
#0 103.1   Downloading nvidia_cusolver_cu11-11.4.0.1-2-py3-none-manylinux1_x86_64.whl (102.6 MB)
#0 111.0      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.6/102.6 MB 12.9 MB/s eta 0:00:00
#0 111.3 Collecting nvidia-cudnn-cu11==8.5.0.96
#0 111.3   Downloading nvidia_cudnn_cu11-8.5.0.96-2-py3-none-manylinux1_x86_64.whl (557.1 MB)
#0 154.6      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 12.9 MB/s eta 0:00:00
#0 155.8 Collecting nvidia-nccl-cu11==2.14.3
#0 155.8   Downloading nvidia_nccl_cu11-2.14.3-py3-none-manylinux1_x86_64.whl (177.1 MB)
#0 169.5      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.1/177.1 MB 12.9 MB/s eta 0:00:00
#0 169.9 Collecting nvidia-cuda-runtime-cu11==11.7.99
#0 169.9   Downloading nvidia_cuda_runtime_cu11-11.7.99-py3-none-manylinux1_x86_64.whl (849 kB)
#0 170.0      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 13.4 MB/s eta 0:00:00
#0 170.0 Collecting nvidia-cuda-nvrtc-cu11==11.7.99
#0 170.1   Downloading nvidia_cuda_nvrtc_cu11-11.7.99-2-py3-none-manylinux1_x86_64.whl (21.0 MB)
#0 171.7      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 12.9 MB/s eta 0:00:00
#0 171.8 Collecting nvidia-cufft-cu11==10.9.0.58
#0 171.8   Downloading nvidia_cufft_cu11-10.9.0.58-py3-none-manylinux1_x86_64.whl (168.4 MB)
#0 184.9      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.4/168.4 MB 12.9 MB/s eta 0:00:00
#0 185.2 Collecting sympy
#0 185.3   Downloading sympy-1.11.1-py3-none-any.whl (6.5 MB)
#0 185.8      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 12.9 MB/s eta 0:00:00
#0 185.8 Collecting jinja2
#0 185.9   Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
#0 185.9      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 15.6 MB/s eta 0:00:00
#0 185.9 Requirement already satisfied: wheel in /usr/local/lib/python3.10/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch->triton==2.0.0) (0.40.0)
#0 185.9 Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch->triton==2.0.0) (67.6.1)
#0 185.9 Collecting MarkupSafe>=2.0
#0 186.0   Downloading MarkupSafe-2.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
#0 186.0 Collecting mpmath>=0.19
#0 186.0   Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
#0 186.1      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 13.7 MB/s eta 0:00:00
#0 186.3 Installing collected packages: mpmath, lit, cmake, typing-extensions, sympy, nvidia-nvtx-cu11, nvidia-nccl-cu11, nvidia-cusparse-cu11, nvidia-curand-cu11, nvidia-cufft-cu11, nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cuda-cupti-cu11, nvidia-cublas-cu11, networkx, MarkupSafe, nvidia-cusolver-cu11, nvidia-cudnn-cu11, jinja2, torch, triton
#0 236.7 Successfully installed MarkupSafe-2.1.2 cmake-3.26.3 jinja2-3.1.2 lit-15.0.6 mpmath-1.3.0 networkx-3.1 nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-cupti-cu11-11.7.101 nvidia-cuda-nvrtc-cu11-11.7.99 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96 nvidia-cufft-cu11-10.9.0.58 nvidia-curand-cu11-10.2.10.91 nvidia-cusolver-cu11-11.4.0.1 nvidia-cusparse-cu11-11.7.4.91 nvidia-nccl-cu11-2.14.3 nvidia-nvtx-cu11-11.7.91 sympy-1.11.1 torch-2.0.0 triton-2.0.0 typing-extensions-4.5.0
#0 236.7 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#0 237.8 + [[ ! -z false ]]
#0 237.8 + '[' false=True ']'
#0 237.8 + TORCH_CUDA_ARCH_LIST=7.5
#0 237.8 + DS_BUILD_OPS=1
#0 237.8 + DS_BUILD_SPARSE_ATTN=0
#0 237.8 + pip install deepspeed==0.8.0
#0 244.9 Collecting deepspeed==0.8.0
#0 245.0   Downloading deepspeed-0.8.0.tar.gz (749 kB)
#0 245.0      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 749.9/749.9 kB 10.2 MB/s eta 0:00:00
#0 245.2   Preparing metadata (setup.py): started
#0 246.8   Preparing metadata (setup.py): finished with status 'error'
#0 246.8   error: subprocess-exited-with-error
#0 246.8   
#0 246.8   × python setup.py egg_info did not run successfully.
#0 246.8   │ exit code: 1
#0 246.8   ╰─> [25 lines of output]
#0 246.8       No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
#0 246.8       Traceback (most recent call last):
#0 246.8         File "<string>", line 2, in <module>
#0 246.8         File "<pip-setuptools-caller>", line 34, in <module>
#0 246.8         File "/tmp/pip-install-4r1p34v4/deepspeed_fb48c919e80f45e1943b3ebe6576ca78/setup.py", line 166, in <module>
#0 246.8           ext_modules.append(builder.builder())
#0 246.8         File "/tmp/pip-install-4r1p34v4/deepspeed_fb48c919e80f45e1943b3ebe6576ca78/op_builder/builder.py", line 601, in builder
#0 246.8           assert_no_cuda_mismatch()
#0 246.8         File "/tmp/pip-install-4r1p34v4/deepspeed_fb48c919e80f45e1943b3ebe6576ca78/op_builder/builder.py", line 89, in assert_no_cuda_mismatch
#0 246.8           cuda_major, cuda_minor = installed_cuda_version()
#0 246.8         File "/tmp/pip-install-4r1p34v4/deepspeed_fb48c919e80f45e1943b3ebe6576ca78/op_builder/builder.py", line 43, in installed_cuda_version
#0 246.8           output = subprocess.check_output([cuda_home + "/bin/nvcc",
#0 246.8         File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
#0 246.8           return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#0 246.8         File "/usr/lib/python3.10/subprocess.py", line 503, in run
#0 246.8           with Popen(*popenargs, **kwargs) as process:
#0 246.8         File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
#0 246.8           self._execute_child(args, executable, preexec_fn, close_fds,
#0 246.8         File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
#0 246.8           raise child_exception_type(errno_num, err_msg, err_filename)
#0 246.8       FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cuda/bin/nvcc'
#0 246.8       [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
#0 246.8       DS_BUILD_OPS=1
#0 246.8        [WARNING]  async_io attempted to use `py-cpuinfo` but failed (exception type: <class 'UnboundLocalError'>, local variable 'get_cpu_info' referenced before assignment), falling back to `lscpu` to get this information.
#0 246.8        [WARNING]  async_io attempted to use `py-cpuinfo` but failed (exception type: <class 'UnboundLocalError'>, local variable 'get_cpu_info' referenced before assignment), falling back to `lscpu` to get this information.
#0 246.8       [end of output]
#0 246.8   
#0 246.8   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 246.8 error: metadata-generation-failed
#0 246.8 
#0 246.8 × Encountered error while generating package metadata.
#0 246.8 ╰─> See above for output.
#0 246.8 
#0 246.8 note: This is an issue with the package mentioned above, not pip.
#0 246.8 hint: See above for details.
------
failed to solve: process "/bin/bash -ceuxo pipefail # deepspeed\npip install triton==${TRITON_VERSION}\n[[ ! -z \"${DEEPSPEED}\" ]] && [ \"${DEEPSPEED}\"=\"True\" ] && TORCH_CUDA_ARCH_LIST=${TORCH_CUDA_ARCH_LIST} DS_BUILD_OPS=${DS_BUILD_OPS} DS_BUILD_SPARSE_ATTN=0 pip install deepspeed==${DEEPSPEED_VERSION}\n" did not complete successfully: exit code: 1
```

This line, it says:

> No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

I've already downloaded those files mentioned earlier and place it under `kohya_ss/data/libs` though, what could be the issue? Any help will be greatly appreciated 🙇🏻‍♂️

**Comment by martinobettucci** [comment]
Sorry for the late answering @junwen-k !

Whatever the version of your card, the kohya scripts requires CUDA 11.x versions to run: that's because the libraries are compiled against them.
You should install CUDE DRIVERS of 12 but CUDE LIBRARIES 11 as this is what it is used by the wheels :-)

**Comment by junwen-k** [comment]
@martinobettucci Thanks for the reply! In the end I resort to using Google Colab to train my LoRA. 🤣 Anyway thanks for answering though.

**Comment by martinobettucci** [comment]
Here is the official COLAB for our repository: https://gist.github.com/martinobettucci/545adb371fcc6a72e8a72e66eae482dc
@junwen-k
